version: 0.1.{build}

image: Visual Studio 2019

environment:
  matrix:
    - generator: '"Visual Studio 14 2015 Win64"'
      build_type: Debug
      compiler_tag: msvc-2015-debug
    - generator: '"Visual Studio 14 2015 Win64"'
      build_type: Release
      compiler_tag: msvc-2015-release
    - generator: '"Visual Studio 16 2019"'
      build_type: Debug
      compiler_tag: msvc-2019-debug
    - generator: '"Visual Studio 16 2019"'
      build_type: Release
      compiler_tag: msvc-2019-release

build_script:
  - ps: >-
      mkdir build,install,deploy

      cd build

      cmake .. -G "$env:generator" -DCMAKE_INSTALL_PREFIX=..\install

      cmake --build . --config $env:build_type

      cmake --build . --target install

after_build:
  - ps: 7z a $env:APPVEYOR_BUILD_FOLDER\deploy\$env:APPVEYOR_PROJECT_NAME-$env:compiler_tag-shared.zip $env:APPVEYOR_BUILD_FOLDER\install\*

artifacts:
  - path: deploy\$(APPVEYOR_PROJECT_NAME)-$(compiler_tag)-shared.zip
    type: zip

skip_commits:
  message: /\[ci skip\]/